site_name: SS220 - Space Station 14 Wiki
repo_url: https://github.com/SerbiaStrong-220/wiki-14
repo_name: SerbiaStrong-220/wiki-14
copyright: Copyright &copy; 2023 SS220. Written and maintained by SS220 community.

theme:
    name: material
    language: ru
    locale: ru
    logo: resources/logo.svg
    favicon: resources/logo.svg
    palette:
        # Palette toggle for dark mode
        - scheme: slate
          primary: black
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
        - scheme: default
          primary: blue grey
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

    features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - navigation.sections
    - navigation.path

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ss220

extra_css:
  - stylesheets/extra.css
  - stylesheets/overrides.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html